apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
spec:
  revisionHistoryLimit: 5
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebappcontainer
          image: 412381781771.dkr.ecr.us-east-1.amazonaws.com/maven-web-application:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: ecr-secret  # Required if your cluster needs authentication to pull from ECR
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002
