version: '3.2'
services:
  springboot:
    image: dockerhandson/maven-web-application:VERSION
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge: